### ISSUE TITLE
✨ feat: 질문 진행 기능

### ISSUE THREAD

**Issue by ninaxlee** [KakaoTech-Get-Crayon/Back-End#7]
# Title

- 질문 진행을 통한 동화 생성 기능을 개발합니다

# TODO

- [ ] FE에서 질문을 요청하기 위한 API 개발
- [ ] AI에 질문을 요청하기 위한 API 개발
- [ ] AI에 이미지 요청하기 위한 API 개발
- [ ] 생성된 동화, 프롬프트의 내용을 DB에 저장

# etc
